# Generated by Django 3.2.11 on 2022-01-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_units_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=200, verbose_name='Картинка, закодированная в Base64'),
        ),
    ]
